language:
   prefix: "&8[&b&lTreasure&3&lChest&8] &7"
   no-permission: "You are not allowed to do this!"
   timeout: "Your looting session lasted too long! You've looted the following:"
   reload: "Plugin reloaded."
   no-player: "This command can only be executed by a player."
   help: "Available commands:"
   help-create: "Create a new treasure chest"
   help-remove: "Remove an existing treasure chest"
   help-reload: "Reload the configuration file"
   no-chest: "You must be looking at a chest to use this command."
   is-treasure: "This block is a Treasure Chest already!"
   created: "Created a new Treasure Chest."
   no-treasure: "This block is not a Treasure Chest."
   removed: "Removed a Treasure Chest."
   already-active: "Please wait. There is a looting session active already!"
   not-your-session: "Please wait. There is a looting session active already!"
   subtitle: "&7Choose 4 Chests To Open "
chests: []
debug: true
version: ${version}