language:
   prefix: "&8[&b&lTreasure&3&lChest&8] &7"
   no-player: "This command can only be executed by a player."
   no-permission: "You are not allowed to do this!"
   no-chest: "Please run this command whilst looking at a &bChest&7."
   no-debug: "Debugging is not enabled right now. Enable it in the configuration file!"
   created-treasure: "Successfully created a &bTreasure Chest&7."
   created-already-treasure: "This block is a &bTreasure Chest&7 already!"
   remove-no-treasure: "This block is not a &bTreasure Chest&7."
   remove-treasure: "Successfully removed a &bTreasure Chest&7."
   debug-type: "Please specify a &bTreasureType&7."
   debug-error-plugin: "Something has gone wrong whilst executing this task. Please contact the creator of this plugin to get this issue resolved!"
   debug-invalid-type: "Invalid &bTreasureType&7."
   reload: "Plugin reloaded."
   help: "Available commands:"
   help-create: "Create a new treasure chest"
   help-remove: "Remove an existing treasure chest"
   help-reload: "Reload the configuration file"
   help-debug: "Additional debug commands:"
   help-debug-set: "Test the pasting of a schematic"
   help-debug-reset: "Set the schematic to default"
   timeout: "Your looting session lasted too long! You've looted the following:"
chests: []
debug: true
version: ${version}