name: ${name}
version: ${version}
description: ${description}
authors: [TheBlockBender, JustDJplease]
main: me.theblockbender.fantastic.treasure.Treasure
depend: [WorldEdit, FastAsyncWorldEdit]
website: https://github.com/JustDJplease/Fantastic-Treasure
database: false

commands:
   treasure:
      description: Manage, create and remove Treasure Chests.
      permission: treasure.admin

permissions:
   treasure.admin:
      description: gives access to the /treasure command
      default: op